version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres-dev:
    image: postgres:15-alpine
    container_name: virtual-memory-board-db-dev
    environment:
      POSTGRES_DB: VirtualMemoryBoard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - app-network-dev
    restart: unless-stopped

  # pgAdmin for Database Management (Optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: virtual-memory-board-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@virtualmemoryboard.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres-dev
    networks:
      - app-network-dev
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local

networks:
  app-network-dev:
    driver: bridge
